// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD7zX-baAoDMFQrjQA_DN_tyceTYcpiGmI',
    appId: '1:379932970084:web:8e6cd76bbd6b3dccf0e371',
    messagingSenderId: '379932970084',
    projectId: 'tarjuman-e-sindh',
    authDomain: 'tarjuman-e-sindh.firebaseapp.com',
    storageBucket: 'tarjuman-e-sindh.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAsGmKr-4zHi81SMqcjpiBMjvy48aKvf2k',
    appId: '1:379932970084:android:c6ffd23ba29e21cbf0e371',
    messagingSenderId: '379932970084',
    projectId: 'tarjuman-e-sindh',
    storageBucket: 'tarjuman-e-sindh.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAGbV1kPmMgYvYDMyTAEl7BcHUZ5Y9hUac',
    appId: '1:379932970084:ios:55bfb74a431f0b28f0e371',
    messagingSenderId: '379932970084',
    projectId: 'tarjuman-e-sindh',
    storageBucket: 'tarjuman-e-sindh.firebasestorage.app',
    iosBundleId: 'com.example.tarjumanESindhAdmin',
  );
}
